Feature/adding forms
RinalinDS/analogtrello pull request #3
Opened 2023-03-06 18:48 UTC by RinalinDS

2023-03-07 12:40 UTC, BeerBaron322 requested changes

2023-03-07 12:40 UTC, BeerBaron322 commented on src/common/AddItemForm/AddBoardForm/ColorPicker/index.tsx
> +          onClick={() => setActiveColor(i)}
move it to a separate function to avoid unnecessary rerenders 
in 99% cases your onclick should look like onClick={handler}

2023-03-07 12:40 UTC, BeerBaron322 commented on src/common/AddItemForm/AddListForm/index.tsx
> +export const StyledField = styled(Field)`
move it to shared components because a similar one is used in addBoadrForm

2023-03-07 12:40 UTC, BeerBaron322 commented on src/common/AddItemForm/AddListForm/index.tsx
> +export const SubmitButton = styled(Button)`
move it to shared components because a similar one is used in addBoadrForm

2023-03-07 12:40 UTC, BeerBaron322 commented on src/common/AddItemForm/AddListForm/index.tsx
> +      {({ values, errors }) => (
move it to separate component

2023-03-07 12:40 UTC, BeerBaron322 commented on src/common/AddItemForm/AddListForm/index.tsx
> +      {({ values, errors }) => (
it's also the same that you use in addTask component

2023-03-07 12:40 UTC, BeerBaron322 commented on src/common/AddItemForm/AddTaskForm/index.tsx
> +        <StyledForm>
move it to separate component, because it's too similar to AddListForm form

2023-03-07 12:40 UTC, BeerBaron322 commented on src/common/AddItemForm/AddTaskForm/index.tsx
> +  isListEmpty: boolean
this prop is not used in comonent

2023-03-07 12:40 UTC, BeerBaron322 commented on src/store/reducers/boardsReducer.ts
> +  currentBoard: {} as BoardType,
why do we use AS here?

2023-03-13 16:19 UTC, BeerBaron322 requested changes

2023-03-13 16:19 UTC, BeerBaron322 commented on src/common/Menu/index.tsx
> +    <div>
if you just need to cover elements in some container you can use React Fragment

2023-03-13 16:19 UTC, BeerBaron322 commented on src/common/AddItemForm/index.tsx
> +export const AddItemForm: FC<AddItemFormPropsType> = memo(
Strange name if it's used for Boards and Items

2023-03-13 16:19 UTC, BeerBaron322 commented on src/common/AddItemForm/index.tsx
> +export const AddItemForm: FC<AddItemFormPropsType> = memo(
Also strange name if it contains logic of displaying title or form

2023-03-13 16:19 UTC, BeerBaron322 commented on src/common/AddItemForm/index.tsx
> +    useEffect(() => {
not clear how it should work
if it's sth for future it should not be in this PR

2023-03-13 16:19 UTC, BeerBaron322 commented on src/common/Menu/index.tsx
> +}> = memo(({ menuList, children, plus, addBoardHandler }) => {
children is not used

2023-03-13 16:19 UTC, BeerBaron322 commented on src/common/Menu/index.tsx
> +        {plus ? (
let's imagine we have 10 icons that can open this menu, so are you going to add here conditions for all the cases?

Let's remove it from here and have it just like needed icon in component and on this icon attach the click handler to open the menu

2023-03-13 16:19 UTC, BeerBaron322 commented on src/common/Modal/DeleteModal/index.tsx
> +export const DeleteModal: FC<DeleteModalPropsType> = memo(
if something is not used you shouldn't add it to the PR

2023-03-13 16:19 UTC, BeerBaron322 commented on src/common/Modal/DeleteModal/index.tsx
> +export const ModalOverlay = styled.div`
Use React Portal for modals

2023-03-13 16:19 UTC, BeerBaron322 commented on src/common/Modal/DeleteModal/index.tsx
> +    const stopPropagationHandler = useCallback((e: SyntheticEvent) => {
you can add stop propagation to the children's click event

and if element doesn't have click event it wont be propagated

2023-03-13 16:19 UTC, BeerBaron322 commented on src/components/Board/index.tsx
> +    setIsPageLoading(false)
it won't work, because your dispatches complete immediately and you immediately make your loader false
I mean dispatch is not async function

2023-03-13 16:19 UTC, BeerBaron322 commented on src/components/Card/CardTitle/index.tsx
> +    if (newTitle !== title) {
also don't forget to trim string

2023-03-13 16:19 UTC, BeerBaron322 commented on src/components/Card/CardTitle/index.tsx
> +        <CloseSharpIcon />
1. Deleting is now working
2. It also executes edit mode for titile

2023-03-13 16:19 UTC, BeerBaron322 commented on src/components/Board/index.tsx
> +        btnText={cards.length < 1 ? 'Add a list' : 'Add another list'}
you can use just `!cards.length`

2023-03-13 16:19 UTC, BeerBaron322 commented on src/components/Card/index.tsx
> +      <CardTitle title={title} callback={onDeleteButtonClick} changeTitle={changCardTitle} />
strange that one handler has some meaningful name and the other is just a callback

2023-03-13 16:19 UTC, BeerBaron322 commented on src/components/Sidebar/index.tsx
> +      navigate(`/boards/${boards.at(-1)?.id}`)
url should be constant

2023-03-13 16:19 UTC, BeerBaron322 commented on src/components/Sidebar/BoardLink/index.tsx
> +  const onClickHandler = () => dispatch(setCurrentBoardId({ id: +id }))
not sure that we have to transform id to number, because in prop type we already expect that id is number

2023-03-13 16:19 UTC, BeerBaron322 commented on src/components/Sidebar/index.tsx
> +  const flag = useAppSelector<boolean>(selectFlag)
should discuss it

2023-03-13 16:19 UTC, BeerBaron322 commented on src/store/reducers/cardsReducer.ts
> +      state.cards.splice(index, 1)
should discuss

2023-03-13 16:19 UTC, BeerBaron322 commented on src/store/selectors/appSelector.tsx
> +export const selectTheme = (state: AppRootStateType) => state.app.theme
btw why do we need themes

2023-03-14 12:28 UTC, RinalinDS commented on src/store/selectors/appSelector.tsx
> +export const selectTheme = (state: AppRootStateType) => state.app.theme
to pass them to ThemeProvider

2023-03-14 12:47 UTC, RinalinDS commented on src/common/AddItemForm/index.tsx
> +    useEffect(() => {
we came to agreement , that this is needed for closing form , when changing boards

2023-03-14 13:38 UTC, RinalinDS commented on src/components/Card/CardTitle/index.tsx
> +        <CloseSharpIcon />
not instantly , but i got the point , added stopProp

2023-03-15 15:57 UTC, merged